function rewardRegionFunction = make_rewardRegionFunction(obj)
%  make_rewardRegionFunction produce a function to make the reward region

width = 2*obj.symbol.radius + obj.reward_region.buffer;

rewardRegionFunction = @(x,y) Screen('FrameOval',...
    obj.windowPointer,...
    obj.reward_region.border_color,...
    CenterRectOnPoint([0 0 width width],x,y)',...
    obj.reward_region.penwidth);
